

spring.datasource.url=jdbc:mysql://auth-db1046.hstgr.io:3306/u119951735_clement

spring.datasource.username=u119951735_ambre_prqt
spring.datasource.password=Ap170512
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configuration Hibernate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=update
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB
spring.datasource.hikari.max-lifetime=15000 
spring.servlet.multipart.location=classpath:/Photos



# Mails
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=ambre.prqt@gmail.com
spring.mail.password=hcqt hlwb uhbf jvcw
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true


spring.jpa.show-sql=true